import React, { createContext, useContext, useState, ReactNode } from 'react';

export interface Language {
  code: string;
  nativeName: string;
  flag?: string;
}

export const languages: Language[] = [
  { code: 'en', nativeName: 'English', flag: '🇺🇸' },
  { code: 'hi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'mr', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'kn', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ta', nativeName: 'தமிழ்', flag: '🇮🇳' }
];

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
  languages: Language[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive translations
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'dashboard': 'Dashboard',
    'transactions': 'Transactions',
    'budget': 'Budget',
    'goals': 'Goals',
    'ai-advisor': 'AI Advisor',
    'settings': 'Settings',
    'welcome': 'Welcome to FinanceAI',
    'ai-companion': 'Your AI-powered financial companion',
    'preferences': 'Preferences',
    'language': 'Language',
    'timezone': 'Time Zone',
    'currency': 'Currency Format',
    'logout': 'Logout from FinanceAI',
    'end-session': 'End your current session',
    'security-tip': 'Security Tip: Always logout from your account when using shared devices.',
    
    // Common UI Elements
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'submit': 'Submit',
    'search': 'Search',
    'filter': 'Filter',
    'close': 'Close',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'no-data': 'No data available',
    'confirm-delete': 'Are you sure you want to delete this item?',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'last-30-days': 'Last 30 days',
    'this-month': 'This month',
    'this-year': 'This year',
    
    // Dashboard
    'welcome-back': 'Welcome back',
    'user': 'User',
    'whats-happening': "Here's what's happening with your finances today",
    'total-income': 'Total Income',
    'total-expenses': 'Total Expenses',
    'net-amount': 'Net Amount',
    'recent-transactions': 'Recent Transactions',
    'view-all': 'View All',
    'quick-actions': 'Quick Actions',
    'add-transaction': 'Add Transaction',
    'monthly-overview': 'Monthly Overview',
    'spending-by-category': 'Spending by Category',
    'balance': 'Balance',
    'income': 'Income',
    'expenses': 'Expenses',
    'savings': 'Savings',
    'budget-status': 'Budget Status',
    'goals-progress': 'Goals Progress',
    
    // Transactions
    'search-transactions': 'Search transactions...',
    'filter-by-type': 'Filter by type',
    'all': 'All',
    'expense': 'Expense',
    'amount': 'Amount',
    'description': 'Description',
    'category': 'Category',
    'date': 'Date',
    'type': 'Type',
    'actions': 'Actions',
    'transaction-added': 'Transaction added successfully',
    'transaction-updated': 'Transaction updated successfully',
    'transaction-deleted': 'Transaction deleted successfully',
    'enter-amount': 'Enter amount',
    'enter-description': 'Enter description',
    'select-category': 'Select category',
    'select-date': 'Select date',
    'transfer': 'Transfer',
    'edit-transaction': 'Edit Transaction',
    'delete-transaction': 'Delete Transaction',
    'confirm-delete-transaction': 'Are you sure you want to delete this transaction?',
    
    // Budget
    'add-budget': 'Add Budget',
    'edit-budget': 'Edit Budget',
    'budget-name': 'Budget Name',
    'budget-amount': 'Budget Amount',
    'spent-amount': 'Spent Amount',
    'period': 'Period',
    'monthly': 'Monthly',
    'yearly': 'Yearly',
    'weekly': 'Weekly',
    'active': 'Active',
    'inactive': 'Inactive',
    'budget-created': 'Budget created successfully',
    'budget-updated': 'Budget updated successfully',
    'budget-deleted': 'Budget deleted successfully',
    'confirm-delete-budget': 'Are you sure you want to delete this budget?',
    'remaining': 'Remaining',
    'over-budget': 'Over Budget',
    'on-track': 'On Track',
    'budget-overview': 'Budget Overview',
    'monitor-spending': 'Monitor your spending and stay on track',
    'total-budget': 'Total Budget',
    'total-spent': 'Total Spent',
    'add-new-budget': 'Add New Budget',
    'budget-name-placeholder': 'e.g., Groceries',
    'active-budget': 'Active budget',
      'update-budget': 'Update Budget',
      'create-budget': 'Create Budget',
      'spent': 'Spent',
    'no-budgets-yet': 'No budgets yet',
    'create-first-budget': 'Create your first budget to start tracking your spending',
    'create-first-budget-button': 'Create Your First Budget',
    'budget-progress': 'Budget Progress',
    'available': 'Available',
    
    // Goals
    'add-goal': 'Add Goal',
    'edit-goal': 'Edit Goal',
    'goal-name': 'Goal Name',
    'target-amount': 'Target Amount',
    'current-amount': 'Current Amount',
    'target-date': 'Target Date',
    'status': 'Status',
    'completed': 'Completed',
    'paused': 'Paused',
    'cancelled': 'Cancelled',
    'progress': 'Progress',
    'goal-created': 'Goal created successfully',
    'goal-updated': 'Goal updated successfully',
    'goal-deleted': 'Goal deleted successfully',
    'confirm-delete-goal': 'Are you sure you want to delete this goal?',
    'days-remaining': 'Days Remaining',
    'goal-description': 'Goal Description',
    'goal-progress': 'Goal Progress',
    'target': 'Target',
    'achieved': 'Achieved',
    'financial-goals': 'Financial Goals',
    'track-progress': 'Track your progress towards financial milestones',
    'add-new-goal': 'Add New Goal',
    'goal-name-placeholder': 'e.g., Emergency Fund',
    'describe-goal': 'Describe your goal...',
    'update-goal': 'Update Goal',
    'create-goal': 'Create Goal',
    'no-goals-yet': 'No goals yet',
    'create-first-goal': 'Create your first financial goal to get started',
    'create-first-goal-button': 'Create Your First Goal',
    
    // AI Advisor
    'ask-ai': 'Ask AI',
    'ai-thinking': 'AI is thinking...',
    'ai-response': 'AI Response',
    'ask-question': 'Ask a question about your finances...',
    'clear-conversation': 'Clear Conversation',
    'recent-queries': 'Recent Queries',
    'ai-categories': 'AI Categories',
    'budgeting-tip': 'Budgeting Tip',
    'savings-advice': 'Savings Advice',
    'investment-tip': 'Investment Tip',
    'financial-insight': 'Financial Insight',
    'get-advice': 'Get Advice',
    'ai-financial-advisor': 'AI Financial Advisor',
    'ai-advisor-description': 'Get personalized financial advice powered by AI. Ask questions about budgeting, investing, saving, or any financial topic.',
    'ask-financial-question': 'Ask your financial question',
    'ai-question-placeholder': 'e.g., How can I save more money? Should I invest in stocks? How much should I have in emergency fund?',
    'quick-questions': 'Quick questions',
    'quick-question-1': 'How can I save more money?',
    'quick-question-2': 'Should I invest in stocks or mutual funds?',
    'quick-question-3': 'How much should I have in emergency fund?',
    'quick-question-4': 'What is the 50/30/20 rule?',
    'quick-question-5': 'How do I create a budget?',
    'quick-question-6': 'When should I start investing?',
    'ai-advice': 'AI Advice',
    'recent-conversations': 'Recent Conversations',
    'previous-ai-interactions': 'Your previous AI interactions',
    'no-conversations-yet': 'No conversations yet',
    'start-asking-question': 'Start by asking a financial question above',
    'failed-load-ai-history': 'Failed to load AI history',
    'failed-get-ai-advice': 'Failed to get AI advice. Please try again.',
    
    // Settings
    'profile': 'Profile',
    'notifications': 'Notifications',
    'security': 'Security',
    'name': 'Name',
    'email': 'Email',
    'phone': 'Phone',
    'avatar': 'Avatar',
    'update-profile': 'Update Profile',
    'email-notifications': 'Email Notifications',
    'push-notifications': 'Push Notifications',
    'sms-notifications': 'SMS Notifications',
    'weekly-report': 'Weekly Report',
    'budget-alerts': 'Budget Alerts',
    'goal-reminders': 'Goal Reminders',
    'theme': 'Theme',
    'light': 'Light',
    'dark': 'Dark',
    'auto': 'Auto',
    'date-format': 'Date Format',
    'two-factor-auth': 'Two-Factor Authentication',
    'change-password': 'Change Password',
    'last-login': 'Last Login',
    'profile-updated': 'Profile updated successfully',
    'settings-saved': 'Settings saved successfully',
    'account-security': 'Account Security',
    'password-changed': 'Password Changed',
    'manage-account-settings': 'Manage your account settings and preferences',
    'profile-information': 'Profile Information',
    'change-avatar': 'Change Avatar',
    'full-name': 'Full Name',
    'notification-preferences': 'Notification Preferences',
    'receive-updates-email': 'Receive updates via email',
    'get-notified-device': 'Get notified on your device',
    'receive-text-messages': 'Receive text messages',
    'get-weekly-summaries': 'Get weekly financial summaries',
    'notify-budget-limits': 'Notify when approaching budget limits',
      'remind-financial-goals': 'Remind about financial goals',
      'app-preferences': 'App Preferences',
      'security-privacy': 'Security & Privacy',
    'update-password-secure': 'Update your password to keep your account secure',
    'add-extra-security': 'Add an extra layer of security to your account',
    'enable-2fa': 'Enable 2FA',
    'data-export': 'Data Export',
    'download-financial-data': 'Download a copy of your financial data',
    'export-data': 'Export Data',
    'save-changes': 'Save Changes',
    'auto-saved': 'Auto-saved',
    
    // Password Change
    'current-password': 'Current Password',
    'new-password': 'New Password',
    'confirm-password': 'Confirm Password',
    'password-mismatch': 'Passwords do not match',
    'password-changed-success': 'Password changed successfully',
    'password-min-length': 'Password must be at least 6 characters',
    
    // Sign In
    'sign-in': 'Sign In',
    'sign-up': 'Sign Up',
    'email-address': 'Email Address',
    'password': 'Password',
    'forgot-password': 'Forgot Password?',
    'login-success': 'Login successful',
    'login-error': 'Login failed',
    'invalid-credentials': 'Invalid credentials',
    'enter-email': 'Enter your email',
    'enter-password': 'Enter your password',
    'remember-me': 'Remember me',
    'dont-have-account': "Don't have an account?",
    'already-have-account': 'Already have an account?'
  },
  hi: {
    // Navigation
    'dashboard': 'डैशबोर्ड',
    'transactions': 'लेन-देन',
    'budget': 'बजट',
    'goals': 'लक्ष्य',
    'ai-advisor': 'एआई सलाहकार',
    'settings': 'सेटिंग्स',
    'welcome': 'FinanceAI में आपका स्वागत है',
    'ai-companion': 'आपका AI-संचालित वित्तीय साथी',
    'preferences': 'प्राथमिकताएं',
    'language': 'भाषा',
    'timezone': 'समय क्षेत्र',
    'currency': 'मुद्रा प्रारूप',
    'logout': 'FinanceAI से लॉगआउट करें',
    'end-session': 'अपना वर्तमान सत्र समाप्त करें',
    'security-tip': 'सुरक्षा टिप: साझा उपकरणों का उपयोग करते समय हमेशा अपने खाते से लॉगआउट करें।',
    
    // Common UI Elements
    'add': 'जोड़ें',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'submit': 'जमा करें',
    'search': 'खोजें',
    'filter': 'फिल्टर',
    'close': 'बंद करें',
    'loading': 'लोड हो रहा है...',
    'error': 'त्रुटि',
    'success': 'सफलता',
    'no-data': 'कोई डेटा उपलब्ध नहीं',
    'confirm-delete': 'क्या आप वाकई इस आइटम को हटाना चाहते हैं?',
    'today': 'आज',
    'yesterday': 'कल',
    'last-30-days': 'पिछले 30 दिन',
    'this-month': 'इस महीने',
    'this-year': 'इस साल',
    
    // Dashboard
    'welcome-back': 'वापस स्वागत है',
    'user': 'उपयोगकर्ता',
    'whats-happening': 'आज आपके वित्त के साथ क्या हो रहा है',
    'total-income': 'कुल आय',
    'total-expenses': 'कुल खर्च',
    'net-amount': 'शुद्ध राशि',
    'recent-transactions': 'हाल के लेन-देन',
    'view-all': 'सभी देखें',
    'quick-actions': 'त्वरित कार्य',
    'add-transaction': 'लेन-देन जोड़ें',
    'monthly-overview': 'मासिक अवलोकन',
    'spending-by-category': 'श्रेणी के अनुसार खर्च',
    'balance': 'बैलेंस',
    'income': 'आय',
    'expenses': 'खर्च',
    'savings': 'बचत',
    'budget-status': 'बजट स्थिति',
    'goals-progress': 'लक्ष्य प्रगति',
    
    // Transactions
    'search-transactions': 'लेन-देन खोजें...',
    'filter-by-type': 'प्रकार से फिल्टर करें',
    'all': 'सभी',
    'expense': 'खर्च',
    'amount': 'राशि',
    'description': 'विवरण',
    'category': 'श्रेणी',
    'date': 'तारीख',
    'type': 'प्रकार',
    'actions': 'कार्य',
    'transaction-added': 'लेन-देन सफलतापूर्वक जोड़ा गया',
    'transaction-updated': 'लेन-देन सफलतापूर्वक अपडेट किया गया',
    'transaction-deleted': 'लेन-देन सफलतापूर्वक हटाया गया',
    'enter-amount': 'राशि दर्ज करें',
    'enter-description': 'विवरण दर्ज करें',
    'select-category': 'श्रेणी चुनें',
    'select-date': 'तारीख चुनें',
    'transfer': 'ट्रांसफर',
    'edit-transaction': 'लेन-देन संपादित करें',
    'delete-transaction': 'लेन-देन हटाएं',
    'confirm-delete-transaction': 'क्या आप वाकई इस लेन-देन को हटाना चाहते हैं?',
    
    // Budget
    'add-budget': 'बजट जोड़ें',
    'edit-budget': 'बजट संपादित करें',
    'budget-name': 'बजट नाम',
    'budget-amount': 'बजट राशि',
    'spent-amount': 'खर्च की गई राशि',
    'period': 'अवधि',
    'monthly': 'मासिक',
    'yearly': 'वार्षिक',
    'weekly': 'साप्ताहिक',
    'active': 'सक्रिय',
    'inactive': 'निष्क्रिय',
    'budget-created': 'बजट सफलतापूर्वक बनाया गया',
    'budget-updated': 'बजट सफलतापूर्वक अपडेट किया गया',
    'budget-deleted': 'बजट सफलतापूर्वक हटाया गया',
    'confirm-delete-budget': 'क्या आप वाकई इस बजट को हटाना चाहते हैं?',
    'remaining': 'शेष',
    'over-budget': 'बजट से अधिक',
    'on-track': 'ट्रैक पर',
    'budget-overview': 'बजट अवलोकन',
    'monitor-spending': 'अपने खर्च पर नज़र रखें और ट्रैक पर रहें',
    'total-budget': 'कुल बजट',
    'total-spent': 'कुल खर्च',
    'add-new-budget': 'नया बजट जोड़ें',
    'budget-name-placeholder': 'जैसे, किराना',
    'active-budget': 'सक्रिय बजट',
      'update-budget': 'बजट अपडेट करें',
      'create-budget': 'बजट बनाएं',
      'spent': 'खर्च',
    'no-budgets-yet': 'अभी तक कोई बजट नहीं',
    'create-first-budget': 'अपने खर्च को ट्रैक करना शुरू करने के लिए अपना पहला बजट बनाएं',
    'create-first-budget-button': 'अपना पहला बजट बनाएं',
    'budget-progress': 'बजट प्रगति',
    'available': 'उपलब्ध',
    
    // Goals
    'add-goal': 'लक्ष्य जोड़ें',
    'edit-goal': 'लक्ष्य संपादित करें',
    'goal-name': 'लक्ष्य नाम',
    'target-amount': 'लक्ष्य राशि',
    'current-amount': 'वर्तमान राशि',
    'target-date': 'लक्ष्य तारीख',
    'status': 'स्थिति',
    'completed': 'पूरा',
    'paused': 'रोका गया',
    'cancelled': 'रद्द',
    'progress': 'प्रगति',
    'goal-created': 'लक्ष्य सफलतापूर्वक बनाया गया',
    'goal-updated': 'लक्ष्य सफलतापूर्वक अपडेट किया गया',
    'goal-deleted': 'लक्ष्य सफलतापूर्वक हटाया गया',
    'confirm-delete-goal': 'क्या आप वाकई इस लक्ष्य को हटाना चाहते हैं?',
    'days-remaining': 'शेष दिन',
    'goal-description': 'लक्ष्य विवरण',
    'goal-progress': 'लक्ष्य प्रगति',
    'target': 'लक्ष्य',
    'achieved': 'प्राप्त',
    'financial-goals': 'वित्तीय लक्ष्य',
    'track-progress': 'वित्तीय मील के पत्थरों की ओर अपनी प्रगति को ट्रैक करें',
    'add-new-goal': 'नया लक्ष्य जोड़ें',
    'goal-name-placeholder': 'जैसे, आपातकालीन फंड',
    'describe-goal': 'अपने लक्ष्य का वर्णन करें...',
    'update-goal': 'लक्ष्य अपडेट करें',
    'create-goal': 'लक्ष्य बनाएं',
    'no-goals-yet': 'अभी तक कोई लक्ष्य नहीं',
    'create-first-goal': 'शुरू करने के लिए अपना पहला वित्तीय लक्ष्य बनाएं',
    'create-first-goal-button': 'अपना पहला लक्ष्य बनाएं',
    
    // AI Advisor
    'ask-ai': 'AI से पूछें',
    'ai-thinking': 'AI सोच रहा है...',
    'ai-response': 'AI प्रतिक्रिया',
    'ask-question': 'अपने वित्त के बारे में कोई सवाल पूछें...',
    'clear-conversation': 'बातचीत साफ करें',
    'recent-queries': 'हाल के प्रश्न',
    'ai-categories': 'AI श्रेणियां',
    'budgeting-tip': 'बजट सुझाव',
    'savings-advice': 'बचत सलाह',
    'investment-tip': 'निवेश सुझाव',
    'financial-insight': 'वित्तीय अंतर्दृष्टि',
    'get-advice': 'सलाह लें',
    'ai-financial-advisor': 'AI वित्तीय सलाहकार',
    'ai-advisor-description': 'AI द्वारा संचालित व्यक्तिगत वित्तीय सलाह प्राप्त करें। बजटिंग, निवेश, बचत या किसी भी वित्तीय विषय के बारे में प्रश्न पूछें।',
    'ask-financial-question': 'अपना वित्तीय प्रश्न पूछें',
    'ai-question-placeholder': 'जैसे, मैं और पैसे कैसे बचा सकता हूं? क्या मुझे स्टॉक में निवेश करना चाहिए? आपातकालीन फंड में कितना होना चाहिए?',
    'quick-questions': 'त्वरित प्रश्न',
    'quick-question-1': 'मैं और पैसे कैसे बचा सकता हूं?',
    'quick-question-2': 'क्या मुझे स्टॉक या म्यूचुअल फंड में निवेश करना चाहिए?',
    'quick-question-3': 'आपातकालीन फंड में कितना होना चाहिए?',
    'quick-question-4': '50/30/20 नियम क्या है?',
    'quick-question-5': 'मैं बजट कैसे बनाऊं?',
    'quick-question-6': 'मुझे निवेश कब शुरू करना चाहिए?',
    'ai-advice': 'AI सलाह',
    'recent-conversations': 'हाल की बातचीत',
    'previous-ai-interactions': 'आपकी पिछली AI बातचीत',
    'no-conversations-yet': 'अभी तक कोई बातचीत नहीं',
    'start-asking-question': 'ऊपर एक वित्तीय प्रश्न पूछकर शुरू करें',
    'failed-load-ai-history': 'AI इतिहास लोड करने में विफल',
    'failed-get-ai-advice': 'AI सलाह प्राप्त करने में विफल। कृपया पुनः प्रयास करें।',
    
    // Settings
    'profile': 'प्रोफाइल',
    'notifications': 'सूचनाएं',
    'security': 'सुरक्षा',
    'name': 'नाम',
    'email': 'ईमेल',
    'phone': 'फोन',
    'avatar': 'अवतार',
    'update-profile': 'प्रोफाइल अपडेट करें',
    'email-notifications': 'ईमेल सूचनाएं',
    'push-notifications': 'पुश सूचनाएं',
    'sms-notifications': 'SMS सूचनाएं',
    'weekly-report': 'साप्ताहिक रिपोर्ट',
    'budget-alerts': 'बजट अलर्ट',
    'goal-reminders': 'लक्ष्य अनुस्मारक',
    'theme': 'थीम',
    'light': 'हल्का',
    'dark': 'गहरा',
    'auto': 'ऑटो',
    'date-format': 'तारीख प्रारूप',
    'two-factor-auth': 'दो-कारक प्रमाणीकरण',
    'change-password': 'पासवर्ड बदलें',
    'last-login': 'अंतिम लॉगिन',
    'profile-updated': 'प्रोफाइल सफलतापूर्वक अपडेट किया गया',
    'settings-saved': 'सेटिंग्स सफलतापूर्वक सहेजी गईं',
    'account-security': 'खाता सुरक्षा',
    'password-changed': 'पासवर्ड बदला गया',
    'manage-account-settings': 'अपनी खाता सेटिंग्स और प्राथमिकताएं प्रबंधित करें',
    'profile-information': 'प्रोफाइल जानकारी',
    'change-avatar': 'अवतार बदलें',
    'full-name': 'पूरा नाम',
    'notification-preferences': 'अधिसूचना प्राथमिकताएं',
    'receive-updates-email': 'ईमेल के माध्यम से अपडेट प्राप्त करें',
    'get-notified-device': 'अपने डिवाइस पर सूचना प्राप्त करें',
    'receive-text-messages': 'टेक्स्ट संदेश प्राप्त करें',
    'get-weekly-summaries': 'साप्ताहिक वित्तीय सारांश प्राप्त करें',
    'notify-budget-limits': 'बजट सीमा के करीब पहुंचने पर सूचित करें',
      'remind-financial-goals': 'वित्तीय लक्ष्यों के बारे में याद दिलाएं',
      'app-preferences': 'ऐप प्राथमिकताएं',
      'security-privacy': 'सुरक्षा और गोपनीयता',
    'update-password-secure': 'अपने खाते को सुरक्षित रखने के लिए अपना पासवर्ड अपडेट करें',
    'add-extra-security': 'अपने खाते में अतिरिक्त सुरक्षा परत जोड़ें',
    'enable-2fa': '2FA सक्षम करें',
    'data-export': 'डेटा निर्यात',
    'download-financial-data': 'अपने वित्तीय डेटा की एक प्रति डाउनलोड करें',
    'export-data': 'डेटा निर्यात करें',
    'save-changes': 'परिवर्तन सहेजें',
    'auto-saved': 'स्वचालित रूप से सहेजा गया',
    
    // Password Change
    'current-password': 'वर्तमान पासवर्ड',
    'new-password': 'नया पासवर्ड',
    'confirm-password': 'पासवर्ड की पुष्टि करें',
    'password-mismatch': 'पासवर्ड मेल नहीं खाते',
    'password-changed-success': 'पासवर्ड सफलतापूर्वक बदल दिया गया',
    'password-min-length': 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    
    // Sign In
    'sign-in': 'साइन इन',
    'sign-up': 'साइन अप',
    'email-address': 'ईमेल पता',
    'password': 'पासवर्ड',
    'forgot-password': 'पासवर्ड भूल गए?',
    'login-success': 'लॉगिन सफल',
    'login-error': 'लॉगिन असफल',
    'invalid-credentials': 'अमान्य क्रेडेंशियल्स',
    'enter-email': 'अपना ईमेल दर्ज करें',
    'enter-password': 'अपना पासवर्ड दर्ज करें',
    'remember-me': 'मुझे याद रखें',
    'dont-have-account': 'खाता नहीं है?',
    'already-have-account': 'पहले से खाता है?'
  },
  mr: {
    // Navigation
    'dashboard': 'डॅशबोर्ड',
    'transactions': 'व्यवहार',
    'budget': 'बजेट',
    'goals': 'उद्दिष्टे',
    'ai-advisor': 'एआय सल्लागार',
    'settings': 'सेटिंग्ज',
    'welcome': 'FinanceAI मध्ये आपले स्वागत आहे',
    'ai-companion': 'तुमचा AI-चालित आर्थिक साथीदार',
    'preferences': 'प्राधान्ये',
    'language': 'भाषा',
    'timezone': 'वेळ क्षेत्र',
    'currency': 'चलन स्वरूप',
    'logout': 'FinanceAI मधून लॉगआउट करा',
    'end-session': 'तुमचा सध्याचा सत्र समाप्त करा',
    'security-tip': 'सुरक्षा टिप: सामायिक उपकरणे वापरताना नेहमी तुमच्या खात्यातून लॉगआउट करा।',
    
    // Common UI Elements
    'add': 'जोडा',
    'edit': 'सुधारा',
    'delete': 'हटवा',
    'save': 'जतन करा',
    'cancel': 'रद्द करा',
    'submit': 'सबमिट करा',
    'search': 'शोधा',
    'filter': 'फिल्टर',
    'close': 'बंद करा',
    'loading': 'लोड होत आहे...',
    'error': 'त्रुटी',
    'success': 'यश',
    'no-data': 'डेटा उपलब्ध नाही',
    'confirm-delete': 'तुम्हाला खात्री आहे की तुम्ही हा आयटम हटवू इच्छिता?',
    'today': 'आज',
    'yesterday': 'काल',
    'last-30-days': 'गेल्या 30 दिवस',
    'this-month': 'या महिन्यात',
    'this-year': 'या वर्षी',
    
    // Dashboard
    'welcome-back': 'पुन्हा स्वागत',
    'user': 'वापरकर्ता',
    'whats-happening': 'आज तुमच्या वित्तासह काय होत आहे',
    'total-income': 'एकूण उत्पन्न',
    'total-expenses': 'एकूण खर्च',
    'net-amount': 'निव्वळ रक्कम',
    'recent-transactions': 'अलीकडील व्यवहार',
    'view-all': 'सर्व पहा',
    'quick-actions': 'द्रुत क्रिया',
    'add-transaction': 'व्यवहार जोडा',
    'monthly-overview': 'मासिक आढावा',
    'spending-by-category': 'श्रेणीनुसार खर्च',
    'balance': 'शिल्लक',
    'income': 'उत्पन्न',
    'expenses': 'खर्च',
    'savings': 'बचत',
    'budget-status': 'बजेट स्थिती',
    'goals-progress': 'उद्दिष्ट प्रगती',
    
    // Transactions
    'search-transactions': 'व्यवहार शोधा...',
    'filter-by-type': 'प्रकारानुसार फिल्टर करा',
    'all': 'सर्व',
    'expense': 'खर्च',
    'amount': 'रक्कम',
    'description': 'वर्णन',
    'category': 'श्रेणी',
    'date': 'तारीख',
    'type': 'प्रकार',
    'actions': 'क्रिया',
    'transaction-added': 'व्यवहार यशस्वीरित्या जोडला',
    'transaction-updated': 'व्यवहार यशस्वीरित्या अद्यतनित केला',
    'transaction-deleted': 'व्यवहार यशस्वीरित्या हटवला',
    'enter-amount': 'रक्कम प्रविष्ट करा',
    'enter-description': 'वर्णन प्रविष्ट करा',
    'select-category': 'श्रेणी निवडा',
    'select-date': 'तारीख निवडा',
    'transfer': 'हस्तांतरण',
    'edit-transaction': 'व्यवहार सुधारा',
    'delete-transaction': 'व्यवहार हटवा',
    'confirm-delete-transaction': 'तुम्हाला खात्री आहे की तुम्ही हा व्यवहार हटवू इच्छिता?',
    
    // Budget
    'add-budget': 'बजेट जोडा',
    'edit-budget': 'बजेट सुधारा',
    'budget-name': 'बजेट नाव',
    'budget-amount': 'बजेट रक्कम',
    'spent-amount': 'खर्च केलेली रक्कम',
    'period': 'कालावधी',
    'monthly': 'मासिक',
    'yearly': 'वार्षिक',
    'weekly': 'साप्ताहिक',
    'active': 'सक्रिय',
    'inactive': 'निष्क्रिय',
    'budget-created': 'बजेट यशस्वीरित्या तयार केला',
    'budget-updated': 'बजेट यशस्वीरित्या अद्यतनित केला',
    'budget-deleted': 'बजेट यशस्वीरित्या हटवला',
    'confirm-delete-budget': 'तुम्हाला खात्री आहे की तुम्ही हा बजेट हटवू इच्छिता?',
    'remaining': 'उरलेले',
    'over-budget': 'बजेटपेक्षा जास्त',
    'on-track': 'मार्गावर',
    'budget-progress': 'बजेट प्रगती',
    'spent': 'खर्च',
    'available': 'उपलब्ध',
    'budget-overview': 'बजेट अवलोकन',
    'monitor-spending': 'तुमच्या खर्चावर लक्ष ठेवा आणि ट्रॅकवर रहा',
    'total-budget': 'एकूण बजेट',
    'total-spent': 'एकूण खर्च',
    'add-new-budget': 'नवीन बजेट जोडा',
    'budget-name-placeholder': 'उदा., किराणा',
    'active-budget': 'सक्रिय बजेट',
      'update-budget': 'बजेट अपडेट करा',
      'create-budget': 'बजेट तयार करा',
      'no-budgets-yet': 'अद्याप कोणतेही बजेट नाही',
    'create-first-budget': 'तुमचा खर्च ट्रॅक करण्यास सुरुवात करण्यासाठी तुमचा पहिला बजेट तयार करा',
    'create-first-budget-button': 'तुमचा पहिला बजेट तयार करा',
    
    // Goals
    'add-goal': 'उद्दिष्ट जोडा',
    'edit-goal': 'उद्दिष्ट सुधारा',
    'goal-name': 'उद्दिष्ट नाव',
    'target-amount': 'लक्ष्य रक्कम',
    'current-amount': 'सध्याची रक्कम',
    'target-date': 'लक्ष्य तारीख',
    'status': 'स्थिती',
    'completed': 'पूर्ण',
    'paused': 'विराम',
    'cancelled': 'रद्द',
    'progress': 'प्रगती',
    'goal-created': 'उद्दिष्ट यशस्वीरित्या तयार केले',
    'goal-updated': 'उद्दिष्ट यशस्वीरित्या अद्यतनित केले',
    'goal-deleted': 'उद्दिष्ट यशस्वीरित्या हटवले',
    'confirm-delete-goal': 'तुम्हाला खात्री आहे की तुम्ही हे उद्दिष्ट हटवू इच्छिता?',
    'days-remaining': 'उरलेले दिवस',
    'goal-description': 'उद्दिष्ट वर्णन',
    'goal-progress': 'उद्दिष्ट प्रगती',
    'target': 'लक्ष्य',
    'achieved': 'प्राप्त',
    'financial-goals': 'आर्थिक उद्दिष्टे',
    'track-progress': 'आर्थिक टप्प्यांकडे तुमच्या प्रगतीचा मागोवा घ्या',
    'add-new-goal': 'नवीन उद्दिष्ट जोडा',
    'goal-name-placeholder': 'उदा., आणीबाणी निधी',
    'describe-goal': 'तुमच्या उद्दिष्टाचे वर्णन करा...',
    'update-goal': 'उद्दिष्ट अपडेट करा',
    'create-goal': 'उद्दिष्ट तयार करा',
    'no-goals-yet': 'अद्याप कोणतेही उद्दिष्ट नाही',
    'create-first-goal': 'सुरुवात करण्यासाठी तुमचे पहिले आर्थिक उद्दिष्ट तयार करा',
    'create-first-goal-button': 'तुमचे पहिले उद्दिष्ट तयार करा',
    
    // AI Advisor
    'ask-ai': 'AI ला विचारा',
    'ai-thinking': 'AI विचार करत आहे...',
    'ai-response': 'AI प्रतिक्रिया',
    'ask-question': 'तुमच्या वित्ताबद्दल प्रश्न विचारा...',
    'clear-conversation': 'संभाषण साफ करा',
    'recent-queries': 'अलीकडील प्रश्न',
    'ai-categories': 'AI श्रेण्या',
    'budgeting-tip': 'बजेट सल्ला',
    'savings-advice': 'बचत सल्ला',
    'investment-tip': 'गुंतवणूक सल्ला',
    'financial-insight': 'आर्थिक अंतर्दृष्टी',
    'get-advice': 'सल्ला घ्या',
    'ai-financial-advisor': 'AI वित्तीय सलाहकार',
    'ai-advisor-description': 'AI द्वारे चालविलेले वैयक्तिक वित्तीय सलाह मिळवा. बजेटिंग, गुंतवणूक, बचत किंवा कोणत्याही वित्तीय विषयाबद्दल प्रश्न विचारा.',
    'ask-financial-question': 'तुमचा वित्तीय प्रश्न विचारा',
    'ai-question-placeholder': 'उदा., मी अधिक पैसे कसे वाचवू शकतो? मला स्टॉकमध्ये गुंतवणूक करावी का? आपत्कालीन निधीत किती असावे?',
    'quick-questions': 'त्वरित प्रश्न',
    'quick-question-1': 'मी अधिक पैसे कसे वाचवू शकतो?',
    'quick-question-2': 'मला स्टॉक किंवा म्युच्युअल फंडमध्ये गुंतवणूक करावी का?',
    'quick-question-3': 'आपत्कालीन निधीत किती असावे?',
    'quick-question-4': '50/30/20 नियम काय आहे?',
    'quick-question-5': 'मी बजेट कसे तयार करू?',
    'quick-question-6': 'मी गुंतवणूक कधी सुरू करावी?',
    'ai-advice': 'AI सल्ला',
    'recent-conversations': 'अलीकडील संभाषणे',
    'previous-ai-interactions': 'तुमचे मागील AI संवाद',
    'no-conversations-yet': 'अद्याप कोणतेही संभाषण नाही',
    'start-asking-question': 'वरील वित्तीय प्रश्न विचारून सुरुवात करा',
    'failed-load-ai-history': 'AI इतिहास लोड करण्यात अयशस्वी',
    'failed-get-ai-advice': 'AI सल्ला मिळविण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    
    // Settings
    'profile': 'प्रोफाइल',
    'notifications': 'सूचना',
    'security': 'सुरक्षा',
    'name': 'नाव',
    'email': 'ईमेल',
    'phone': 'फोन',
    'avatar': 'अवतार',
    'update-profile': 'प्रोफाइल अद्यतनित करा',
    'email-notifications': 'ईमेल सूचना',
    'push-notifications': 'पुश सूचना',
    'sms-notifications': 'SMS सूचना',
    'weekly-report': 'साप्ताहिक अहवाल',
    'budget-alerts': 'बजेट अलर्ट',
    'goal-reminders': 'उद्दिष्ट आठवण',
    'theme': 'थीम',
    'light': 'हलका',
    'dark': 'गडद',
    'auto': 'ऑटो',
    'date-format': 'तारीख स्वरूप',
    'two-factor-auth': 'दोन-कारक प्रमाणीकरण',
    'change-password': 'पासवर्ड बदला',
    'last-login': 'शेवटचा लॉगिन',
    'profile-updated': 'प्रोफाइल यशस्वीरित्या अद्यतनित केले',
    'settings-saved': 'सेटिंग्ज यशस्वीरित्या जतन केल्या',
    'account-security': 'खाते सुरक्षा',
    'password-changed': 'पासवर्ड बदलला',
    'manage-account-settings': 'तुमच्या खाते सेटिंग्ज आणि प्राधान्ये व्यवस्थापित करा',
    'profile-information': 'प्रोफाइल माहिती',
    'change-avatar': 'अवतार बदला',
    'full-name': 'पूर्ण नाव',
    'notification-preferences': 'अधिसूचना प्राधान्ये',
    'receive-updates-email': 'ईमेलद्वारे अपडेट्स प्राप्त करा',
    'get-notified-device': 'तुमच्या डिव्हाइसवर सूचना प्राप्त करा',
    'receive-text-messages': 'टेक्स्ट संदेश प्राप्त करा',
    'get-weekly-summaries': 'साप्ताहिक आर्थिक सारांश प्राप्त करा',
    'notify-budget-limits': 'बजेट मर्यादेजवळ पोहोचल्यावर सूचित करा',
      'remind-financial-goals': 'आर्थिक उद्दिष्टांबद्दल आठवण द्या',
      'app-preferences': 'अॅप प्राधान्ये',
      'security-privacy': 'सुरक्षा आणि गोपनीयता',
    'update-password-secure': 'तुमचे खाते सुरक्षित ठेवण्यासाठी तुमचा पासवर्ड अपडेट करा',
    'add-extra-security': 'तुमच्या खात्यात अतिरिक्त सुरक्षा स्तर जोडा',
    'enable-2fa': '2FA सक्षम करा',
    'data-export': 'डेटा निर्यात',
    'download-financial-data': 'तुमच्या आर्थिक डेटाची एक प्रत डाउनलोड करा',
    'export-data': 'डेटा निर्यात करा',
    'save-changes': 'बदल जतन करा',
    'auto-saved': 'स्वयंचलितपणे जतन केले',
    
    // Password Change
    'current-password': 'सध्याचा पासवर्ड',
    'new-password': 'नवीन पासवर्ड',
    'confirm-password': 'पासवर्डची पुष्टी करा',
    'password-mismatch': 'पासवर्ड जुळत नाहीत',
    'password-changed-success': 'पासवर्ड यशस्वीरित्या बदलला',
    'password-min-length': 'पासवर्ड किमान 6 वर्णांचा असावा',
    
    // Sign In
    'sign-in': 'साइन इन',
    'sign-up': 'साइन अप',
    'email-address': 'ईमेल पत्ता',
    'password': 'पासवर्ड',
    'forgot-password': 'पासवर्ड विसरलात?',
    'login-success': 'लॉगिन यशस्वी',
    'login-error': 'लॉगिन अयशस्वी',
    'invalid-credentials': 'अवैध क्रेडेन्शियल्स',
    'enter-email': 'तुमचा ईमेल प्रविष्ट करा',
    'enter-password': 'तुमचा पासवर्ड प्रविष्ट करा',
    'remember-me': 'मला आठवा',
    'dont-have-account': 'खाते नाही?',
    'already-have-account': 'आधीच खाते आहे?'
  },
  kn: {
    // Navigation
    'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'transactions': 'ವ್ಯವಹಾರಗಳು',
    'budget': 'ಬಜೆಟ್',
    'goals': 'ಗುರಿಗಳು',
    'ai-advisor': 'ಎಐ ಸಲಹೆಗಾರ',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'welcome': 'FinanceAI ಗೆ ಸುಸ್ವಾಗತ',
    'ai-companion': 'ನಿಮ್ಮ ಎಐ-ಚಾಲಿತ ಹಣಕಾಸು ಸಂಗಾತಿ',
    'preferences': 'ಆದ್ಯತೆಗಳು',
    'language': 'ಭಾಷೆ',
    'timezone': 'ಸಮಯ ವಲಯ',
    'currency': 'ಕರೆನ್ಸಿ ಫಾರ್ಮ್ಯಾಟ್',
    'logout': 'FinanceAI ನಿಂದ ಲಾಗ್‌ಔಟ್ ಮಾಡಿ',
    'end-session': 'ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸೆಷನ್ ಕೊನೆಗೊಳಿಸಿ',
    'security-tip': 'ಸುರಕ್ಷತೆ ಸಲಹೆ: ಹಂಚಿಕೊಂಡ ಸಾಧನಗಳನ್ನು ಬಳಸುವಾಗ ಯಾವಾಗಲೂ ನಿಮ್ಮ ಖಾತೆಯಿಂದ ಲಾಗ್‌ಔಟ್ ಮಾಡಿ.',
    
    // Common UI Elements
    'add': 'ಸೇರಿಸಿ',
    'edit': 'ಸಂಪಾದಿಸಿ',
    'delete': 'ಅಳಿಸಿ',
    'save': 'ಉಳಿಸಿ',
    'cancel': 'ರದ್ದುಗೊಳಿಸಿ',
    'submit': 'ಸಲ್ಲಿಸಿ',
    'search': 'ಹುಡುಕಿ',
    'filter': 'ಫಿಲ್ಟರ್',
    'close': 'ಮುಚ್ಚಿ',
    'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'error': 'ದೋಷ',
    'success': 'ಯಶಸ್ಸು',
    'no-data': 'ದತ್ತಾಂಶ ಲಭ್ಯವಿಲ್ಲ',
    'confirm-delete': 'ನೀವು ಖಚಿತವಾಗಿ ಈ ಐಟಂ ಅನ್ನು ಅಳಿಸಲು ಬಯಸುತ್ತೀರಾ?',
    'today': 'ಇಂದು',
    'yesterday': 'ನಿನ್ನೆ',
    'last-30-days': 'ಕಳೆದ 30 ದಿನಗಳು',
    'this-month': 'ಈ ತಿಂಗಳು',
    'this-year': 'ಈ ವರ್ಷ',
    
    // Dashboard
    'welcome-back': 'ಮತ್ತೆ ಸುಸ್ವಾಗತ',
    'user': 'ಬಳಕೆದಾರ',
    'whats-happening': 'ಇಂದು ನಿಮ್ಮ ಹಣಕಾಸಿನೊಂದಿಗೆ ಏನು ನಡೆಯುತ್ತಿದೆ',
    'total-income': 'ಒಟ್ಟು ಆದಾಯ',
    'total-expenses': 'ಒಟ್ಟು ವೆಚ್ಚ',
    'net-amount': 'ನಿವ್ವಳ ಮೊತ್ತ',
    'recent-transactions': 'ಇತ್ತೀಚಿನ ವ್ಯವಹಾರಗಳು',
    'view-all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
    'quick-actions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    'add-transaction': 'ವ್ಯವಹಾರ ಸೇರಿಸಿ',
    'monthly-overview': 'ಮಾಸಿಕ ಅವಲೋಕನ',
    'spending-by-category': 'ವರ್ಗದ ಪ್ರಕಾರ ವೆಚ್ಚ',
    'balance': 'ಬ್ಯಾಲೆನ್ಸ್',
    'income': 'ಆದಾಯ',
    'expenses': 'ವೆಚ್ಚ',
    'savings': 'ಉಳಿತಾಯ',
    'budget-status': 'ಬಜೆಟ್ ಸ್ಥಿತಿ',
    'goals-progress': 'ಗುರಿಗಳ ಪ್ರಗತಿ',
    
    // Transactions
    'search-transactions': 'ವ್ಯವಹಾರಗಳನ್ನು ಹುಡುಕಿ...',
    'filter-by-type': 'ಪ್ರಕಾರದಿಂದ ಫಿಲ್ಟರ್ ಮಾಡಿ',
    'all': 'ಎಲ್ಲ',
    'expense': 'ವೆಚ್ಚ',
    'amount': 'ಮೊತ್ತ',
    'description': 'ವಿವರಣೆ',
    'category': 'ವರ್ಗ',
    'date': 'ದಿನಾಂಕ',
    'type': 'ಪ್ರಕಾರ',
    'actions': 'ಕ್ರಿಯೆಗಳು',
    'transaction-added': 'ವ್ಯವಹಾರ ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ',
    'transaction-updated': 'ವ್ಯವಹಾರ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    'transaction-deleted': 'ವ್ಯವಹಾರ ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ',
    'enter-amount': 'ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ',
    'enter-description': 'ವಿವರಣೆಯನ್ನು ನಮೂದಿಸಿ',
    'select-category': 'ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'select-date': 'ದಿನಾಂಕವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'transfer': 'ವರ್ಗಾವಣೆ',
    'edit-transaction': 'ವ್ಯವಹಾರ ಸಂಪಾದಿಸಿ',
    'delete-transaction': 'ವ್ಯವಹಾರ ಅಳಿಸಿ',
    'confirm-delete-transaction': 'ನೀವು ಖಚಿತವಾಗಿ ಈ ವ್ಯವಹಾರವನ್ನು ಅಳಿಸಲು ಬಯಸುತ್ತೀರಾ?',
    
    // Budget
    'add-budget': 'ಬಜೆಟ್ ಸೇರಿಸಿ',
    'edit-budget': 'ಬಜೆಟ್ ಸಂಪಾದಿಸಿ',
    'budget-name': 'ಬಜೆಟ್ ಹೆಸರು',
    'budget-amount': 'ಬಜೆಟ್ ಮೊತ್ತ',
    'spent-amount': 'ಖರ್ಚು ಮಾಡಿದ ಮೊತ್ತ',
    'period': 'ಅವಧಿ',
    'monthly': 'ಮಾಸಿಕ',
    'yearly': 'ವಾರ್ಷಿಕ',
    'weekly': 'ಸಾಪ್ತಾಹಿಕ',
    'active': 'ಸಕ್ರಿಯ',
    'inactive': 'ನಿಷ್ಕ್ರಿಯ',
    'budget-created': 'ಬಜೆಟ್ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ',
    'budget-updated': 'ಬಜೆಟ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    'budget-deleted': 'ಬಜೆಟ್ ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ',
    'confirm-delete-budget': 'ನೀವು ಖಚಿತವಾಗಿ ಈ ಬಜೆಟ್ ಅನ್ನು ಅಳಿಸಲು ಬಯಸುತ್ತೀರಾ?',
    'remaining': 'ಉಳಿದಿರುವ',
    'over-budget': 'ಬಜೆಟ್ ಮೀರಿ',
    'on-track': 'ಟ್ರ್ಯಾಕ್‌ನಲ್ಲಿ',
    'budget-progress': 'ಬಜೆಟ್ ಪ್ರಗತಿ',
    'spent': 'ಖರ್ಚು',
    'available': 'ಲಭ್ಯ',
    'budget-overview': 'ಬಜೆಟ್ ಅವಲೋಕನ',
    'monitor-spending': 'ನಿಮ್ಮ ಖರ್ಚನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್‌ನಲ್ಲಿ ಇರಿ',
    'total-budget': 'ಒಟ್ಟು ಬಜೆಟ್',
    'total-spent': 'ಒಟ್ಟು ಖರ್ಚು',
    'add-new-budget': 'ಹೊಸ ಬಜೆಟ್ ಸೇರಿಸಿ',
    'budget-name-placeholder': 'ಉದಾ., ಕಿರಾಣಿ',
    'active-budget': 'ಸಕ್ರಿಯ ಬಜೆಟ್',
      'update-budget': 'ಬಜೆಟ್ ನವೀಕರಿಸಿ',
      'create-budget': 'ಬಜೆಟ್ ರಚಿಸಿ',
      'no-budgets-yet': 'ಇನ್ನೂ ಯಾವುದೇ ಬಜೆಟ್ ಇಲ್ಲ',
    'create-first-budget': 'ನಿಮ್ಮ ಖರ್ಚನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಬಜೆಟ್ ರಚಿಸಿ',
    'create-first-budget-button': 'ನಿಮ್ಮ ಮೊದಲ ಬಜೆಟ್ ರಚಿಸಿ',
    
    // Goals
    'add-goal': 'ಗುರಿ ಸೇರಿಸಿ',
    'edit-goal': 'ಗುರಿ ಸಂಪಾದಿಸಿ',
    'goal-name': 'ಗುರಿ ಹೆಸರು',
    'target-amount': 'ಲಕ್ಷ್ಯ ಮೊತ್ತ',
    'current-amount': 'ಪ್ರಸ್ತುತ ಮೊತ್ತ',
    'target-date': 'ಲಕ್ಷ್ಯ ದಿನಾಂಕ',
    'status': 'ಸ್ಥಿತಿ',
    'completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'paused': 'ಆಡಿಸಲಾಗಿದೆ',
    'cancelled': 'ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ',
    'progress': 'ಪ್ರಗತಿ',
    'goal-created': 'ಗುರಿ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ',
    'goal-updated': 'ಗುರಿ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    'goal-deleted': 'ಗುರಿ ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ',
    'confirm-delete-goal': 'ನೀವು ಖಚಿತವಾಗಿ ಈ ಗುರಿಯನ್ನು ಅಳಿಸಲು ಬಯಸುತ್ತೀರಾ?',
    'days-remaining': 'ಉಳಿದಿರುವ ದಿನಗಳು',
    'goal-description': 'ಗುರಿ ವಿವರಣೆ',
    'goal-progress': 'ಗುರಿ ಪ್ರಗತಿ',
    'target': 'ಲಕ್ಷ್ಯ',
    'achieved': 'ಸಾಧಿಸಲಾಗಿದೆ',
    'financial-goals': 'ಹಣಕಾಸು ಗುರಿಗಳು',
    'track-progress': 'ಹಣಕಾಸು ಮೈಲಿಗಲ್ಲುಗಳ ಕಡೆಗೆ ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'add-new-goal': 'ಹೊಸ ಗುರಿ ಸೇರಿಸಿ',
    'goal-name-placeholder': 'ಉದಾ., ತುರ್ತು ನಿಧಿ',
    'describe-goal': 'ನಿಮ್ಮ ಗುರಿಯನ್ನು ವಿವರಿಸಿ...',
    'update-goal': 'ಗುರಿ ನವೀಕರಿಸಿ',
    'create-goal': 'ಗುರಿ ರಚಿಸಿ',
    'no-goals-yet': 'ಇನ್ನೂ ಯಾವುದೇ ಗುರಿಗಳು ಇಲ್ಲ',
    'create-first-goal': 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಮೊದಲ ಹಣಕಾಸು ಗುರಿಯನ್ನು ರಚಿಸಿ',
    'create-first-goal-button': 'ನಿಮ್ಮ ಮೊದಲ ಗುರಿಯನ್ನು ರಚಿಸಿ',
    
    // AI Advisor
    'ask-ai': 'ಎಐಗೆ ಕೇಳಿ',
    'ai-thinking': 'ಎಐ ಯೋಚಿಸುತ್ತಿದೆ...',
    'ai-response': 'ಎಐ ಪ್ರತಿಕ್ರಿಯೆ',
    'ask-question': 'ನಿಮ್ಮ ಹಣಕಾಸಿನ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ...',
    'clear-conversation': 'ಸಂಭಾಷಣೆಯನ್ನು ತೆರವುಗೊಳಿಸಿ',
    'recent-queries': 'ಇತ್ತೀಚಿನ ಪ್ರಶ್ನೆಗಳು',
    'ai-categories': 'ಎಐ ವರ್ಗಗಳು',
    'budgeting-tip': 'ಬಜೆಟ್ ಸಲಹೆ',
    'savings-advice': 'ಉಳಿತಾಯ ಸಲಹೆ',
    'investment-tip': 'ಹೂಡಿಕೆ ಸಲಹೆ',
    'financial-insight': 'ಹಣಕಾಸು ಅಂತರ್ದೃಷ್ಟಿ',
    'get-advice': 'ಸಲಹೆ ಪಡೆಯಿರಿ',
    'ai-financial-advisor': 'ಎಐ ಹಣಕಾಸು ಸಲಹೆಗಾರ',
    'ai-advisor-description': 'ಎಐ ಚಾಲಿತ ವೈಯಕ್ತಿಕ ಹಣಕಾಸು ಸಲಹೆ ಪಡೆಯಿರಿ. ಬಜೆಟ್, ಹೂಡಿಕೆ, ಉಳಿತಾಯ ಅಥವಾ ಯಾವುದೇ ಹಣಕಾಸು ವಿಷಯದ ಬಗ್ಗೆ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ.',
    'ask-financial-question': 'ನಿಮ್ಮ ಹಣಕಾಸು ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ',
    'ai-question-placeholder': 'ಉದಾ., ನಾನು ಹೆಚ್ಚು ಹಣವನ್ನು ಹೇಗೆ ಉಳಿಸಬಹುದು? ನಾನು ಸ್ಟಾಕ್‌ಗಳಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡಬೇಕೇ? ತುರ್ತು ನಿಧಿಯಲ್ಲಿ ಎಷ್ಟು ಇರಬೇಕು?',
    'quick-questions': 'ತ್ವರಿತ ಪ್ರಶ್ನೆಗಳು',
    'quick-question-1': 'ನಾನು ಹೆಚ್ಚು ಹಣವನ್ನು ಹೇಗೆ ಉಳಿಸಬಹುದು?',
    'quick-question-2': 'ನಾನು ಸ್ಟಾಕ್‌ಗಳು ಅಥವಾ ಮ್ಯೂಚುಯಲ್ ಫಂಡ್‌ಗಳಲ್ಲಿ ಹೂಡಿಕೆ ಮಾಡಬೇಕೇ?',
    'quick-question-3': 'ತುರ್ತು ನಿಧಿಯಲ್ಲಿ ಎಷ್ಟು ಇರಬೇಕು?',
    'quick-question-4': '50/30/20 ನಿಯಮ ಯಾವುದು?',
    'quick-question-5': 'ನಾನು ಬಜೆಟ್ ಅನ್ನು ಹೇಗೆ ರಚಿಸಬಹುದು?',
    'quick-question-6': 'ನಾನು ಹೂಡಿಕೆಯನ್ನು ಯಾವಾಗ ಪ್ರಾರಂಭಿಸಬೇಕು?',
    'ai-advice': 'ಎಐ ಸಲಹೆ',
    'recent-conversations': 'ಇತ್ತೀಚಿನ ಸಂಭಾಷಣೆಗಳು',
    'previous-ai-interactions': 'ನಿಮ್ಮ ಹಿಂದಿನ ಎಐ ಸಂವಾದಗಳು',
    'no-conversations-yet': 'ಇನ್ನೂ ಯಾವುದೇ ಸಂಭಾಷಣೆಗಳು ಇಲ್ಲ',
    'start-asking-question': 'ಮೇಲೆ ಹಣಕಾಸು ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳುವ ಮೂಲಕ ಪ್ರಾರಂಭಿಸಿ',
    'failed-load-ai-history': 'ಎಐ ಇತಿಹಾಸವನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ',
    'failed-get-ai-advice': 'ಎಐ ಸಲಹೆಯನ್ನು ಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    
    // Settings
    'profile': 'ಪ್ರೊಫೈಲ್',
    'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'security': 'ಭದ್ರತೆ',
    'name': 'ಹೆಸರು',
    'email': 'ಇಮೇಲ್',
    'phone': 'ಫೋನ್',
    'avatar': 'ಅವತಾರ',
    'update-profile': 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ',
    'email-notifications': 'ಇಮೇಲ್ ಅಧಿಸೂಚನೆಗಳು',
    'push-notifications': 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು',
    'sms-notifications': 'SMS ಅಧಿಸೂಚನೆಗಳು',
    'weekly-report': 'ಸಾಪ್ತಾಹಿಕ ವರದಿ',
    'budget-alerts': 'ಬಜೆಟ್ ಎಚ್ಚರಿಕೆಗಳು',
    'goal-reminders': 'ಗುರಿ ನೆನಪುಗಳು',
    'theme': 'ಥೀಮ್',
    'light': 'ತೆಳು',
    'dark': 'ಗಾಢ',
    'auto': 'ಸ್ವಯಂ',
    'date-format': 'ದಿನಾಂಕ ಸ್ವರೂಪ',
    'two-factor-auth': 'ಎರಡು-ಅಂಶ ದೃಢೀಕರಣ',
    'change-password': 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ',
    'last-login': 'ಕೊನೆಯ ಲಾಗಿನ್',
    'profile-updated': 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    'settings-saved': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ',
    'account-security': 'ಖಾತೆ ಭದ್ರತೆ',
    'password-changed': 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಲಾಗಿದೆ',
    'manage-account-settings': 'ನಿಮ್ಮ ಖಾತೆ ಸೆಟ್ಟಿಂಗ್ಗಳು ಮತ್ತು ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'profile-information': 'ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿ',
    'change-avatar': 'ಅವತಾರ ಬದಲಾಯಿಸಿ',
    'full-name': 'ಪೂರ್ಣ ಹೆಸರು',
    'notification-preferences': 'ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು',
    'receive-updates-email': 'ಇಮೇಲ್ ಮೂಲಕ ನವೀಕರಣಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
    'get-notified-device': 'ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿ ಅಧಿಸೂಚನೆ ಪಡೆಯಿರಿ',
    'receive-text-messages': 'ಟೆಕ್ಸ್ಟ್ ಸಂದೇಶಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
    'get-weekly-summaries': 'ಸಾಪ್ತಾಹಿಕ ಹಣಕಾಸು ಸಾರಾಂಶಗಳನ್ನು ಪಡೆಯಿರಿ',
    'notify-budget-limits': 'ಬಜೆಟ್ ಮಿತಿಗಳನ್ನು ತಲುಪಿದಾಗ ಅಧಿಸೂಚಿಸಿ',
      'remind-financial-goals': 'ಹಣಕಾಸು ಗುರಿಗಳ ಬಗ್ಗೆ ನೆನಪಿಸಿ',
      'app-preferences': 'ಅಪ್ಲಿಕೇಶನ್ ಆದ್ಯತೆಗಳು',
      'security-privacy': 'ಭದ್ರತೆ ಮತ್ತು ಗೌಪ್ಯತೆ',
    'update-password-secure': 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಸುರಕ್ಷಿತವಾಗಿಡಲು ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ಅನ್ನು ನವೀಕರಿಸಿ',
    'add-extra-security': 'ನಿಮ್ಮ ಖಾತೆಗೆ ಹೆಚ್ಚುವರಿ ಭದ್ರತಾ ಪದರವನ್ನು ಸೇರಿಸಿ',
    'enable-2fa': '2FA ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'data-export': 'ಡೇಟಾ ರಫ್ತು',
    'download-financial-data': 'ನಿಮ್ಮ ಹಣಕಾಸು ಡೇಟಾದ ಪ್ರತಿಯನ್ನು ಡೌನ್ಲೋಡ್ ಮಾಡಿ',
    'export-data': 'ಡೇಟಾ ರಫ್ತು ಮಾಡಿ',
    'save-changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    'auto-saved': 'ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಉಳಿಸಲಾಗಿದೆ',
    
    // Password Change
    'current-password': 'ಪ್ರಸ್ತುತ ಪಾಸ್ವರ್ಡ್',
    'new-password': 'ಹೊಸ ಪಾಸ್ವರ್ಡ್',
    'confirm-password': 'ಪಾಸ್ವರ್ಡ್ ಅನ್ನು ದೃಢೀಕರಿಸಿ',
    'password-mismatch': 'ಪಾಸ್ವರ್ಡ್‌ಗಳು ಹೊಂದಾಣಿಕೆಯಾಗುವುದಿಲ್ಲ',
    'password-changed-success': 'ಪಾಸ್ವರ್ಡ್ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ',
    'password-min-length': 'ಪಾಸ್ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು',
    
    // Sign In
    'sign-in': 'ಸೈನ್ ಇನ್',
    'sign-up': 'ಸೈನ್ ಅಪ್',
    'email-address': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'password': 'ಪಾಸ್‌ವರ್ಡ್',
    'forgot-password': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
    'login-success': 'ಲಾಗಿನ್ ಯಶಸ್ವಿ',
    'login-error': 'ಲಾಗಿನ್ ವಿಫಲ',
    'invalid-credentials': 'ಅಮಾನ್ಯ ಕ್ರೆಡೆನ್‌ಷಿಯಲ್‌ಗಳು',
    'enter-email': 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    'enter-password': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    'remember-me': 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    'dont-have-account': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'already-have-account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?'
  },
  ta: {
    // Navigation
    'dashboard': 'டாஷ்போர்டு',
    'transactions': 'பரிவர்த்தனைகள்',
    'budget': 'பட்ஜெட்',
    'goals': 'இலக்குகள்',
    'ai-advisor': 'ஏஐ ஆலோசகர்',
    'settings': 'அமைப்புகள்',
    'welcome': 'FinanceAI க்கு வரவேற்கிறோம்',
    'ai-companion': 'உங்கள் ஏஐ-இயக்கப்பட்ட நிதி துணை',
    'preferences': 'விருப்பத்தேர்வுகள்',
    'language': 'மொழி',
    'timezone': 'நேர மண்டலம்',
    'currency': 'நாணய வடிவம்',
    'logout': 'FinanceAI இலிருந்து வெளியேறு',
    'end-session': 'உங்கள் தற்போதைய அமர்வை முடிக்கவும்',
    'security-tip': 'பாதுகாப்பு குறிப்பு: பகிர்ந்த சாதனங்களைப் பயன்படுத்தும்போது எப்போதும் உங்கள் கணக்கிலிருந்து வெளியேறுங்கள்.',
    
    // Common UI Elements
    'add': 'சேர்க்கவும்',
    'edit': 'திருத்தவும்',
    'delete': 'நீக்கவும்',
    'save': 'சேமிக்கவும்',
    'cancel': 'ரத்து செய்யவும்',
    'submit': 'சமர்ப்பிக்கவும்',
    'search': 'தேடவும்',
    'filter': 'வடிகட்டவும்',
    'close': 'மூடவும்',
    'loading': 'ஏற்றுகிறது...',
    'error': 'பிழை',
    'success': 'வெற்றி',
    'no-data': 'தரவு இல்லை',
    'confirm-delete': 'இந்த உருப்படியை நீக்க விரும்புகிறீர்களா?',
    'today': 'இன்று',
    'yesterday': 'நேற்று',
    'last-30-days': 'கடந்த 30 நாட்கள்',
    'this-month': 'இந்த மாதம்',
    'this-year': 'இந்த ஆண்டு',
    
    // Dashboard
    'welcome-back': 'மீண்டும் வரவேற்கிறோம்',
    'user': 'பயனர்',
    'whats-happening': 'இன்று உங்கள் நிதியுடன் என்ன நடக்கிறது',
    'total-income': 'மொத்த வருமானம்',
    'total-expenses': 'மொத்த செலவுகள்',
    'net-amount': 'நிகர தொகை',
    'recent-transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
    'view-all': 'அனைத்தையும் பார்க்கவும்',
    'quick-actions': 'விரைவு செயல்கள்',
    'add-transaction': 'பரிவர்த்தனை சேர்க்கவும்',
    'monthly-overview': 'மாதாந்திர கண்ணோட்டம்',
    'spending-by-category': 'வகை வாரியாக செலவு',
    'balance': 'இருப்பு',
    'income': 'வருமானம்',
    'expenses': 'செலவுகள்',
    'savings': 'சேமிப்பு',
    'budget-status': 'பட்ஜெட் நிலை',
    'goals-progress': 'இலக்கு முன்னேற்றம்',
    
    // Transactions
    'search-transactions': 'பரிவர்த்தனைகளை தேடவும்...',
    'filter-by-type': 'வகை வாரியாக வடிகட்டவும்',
    'all': 'அனைத்தும்',
    'expense': 'செலவு',
    'amount': 'தொகை',
    'description': 'விளக்கம்',
    'category': 'வகை',
    'date': 'தேதி',
    'type': 'வகை',
    'actions': 'செயல்கள்',
    'transaction-added': 'பரிவர்த்தனை வெற்றிகரமாக சேர்க்கப்பட்டது',
    'transaction-updated': 'பரிவர்த்தனை வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    'transaction-deleted': 'பரிவர்த்தனை வெற்றிகரமாக நீக்கப்பட்டது',
    'enter-amount': 'தொகையை உள்ளிடவும்',
    'enter-description': 'விளக்கத்தை உள்ளிடவும்',
    'select-category': 'வகையை தேர்ந்தெடுக்கவும்',
    'select-date': 'தேதியை தேர்ந்தெடுக்கவும்',
    'transfer': 'பரிமாற்றம்',
    'edit-transaction': 'பரிவர்த்தனையை திருத்தவும்',
    'delete-transaction': 'பரிவர்த்தனையை நீக்கவும்',
    'confirm-delete-transaction': 'இந்த பரிவர்த்தனையை நீக்க விரும்புகிறீர்களா?',
    
    // Budget
    'add-budget': 'பட்ஜெட் சேர்க்கவும்',
    'edit-budget': 'பட்ஜெட்டை திருத்தவும்',
    'budget-name': 'பட்ஜெட் பெயர்',
    'budget-amount': 'பட்ஜெட் தொகை',
    'spent-amount': 'செலவழிக்கப்பட்ட தொகை',
    'period': 'காலம்',
    'monthly': 'மாதாந்திர',
    'yearly': 'ஆண்டு',
    'weekly': 'வாராந்திர',
    'active': 'செயலில்',
    'inactive': 'செயலற்ற',
    'budget-created': 'பட்ஜெட் வெற்றிகரமாக உருவாக்கப்பட்டது',
    'budget-updated': 'பட்ஜெட் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    'budget-deleted': 'பட்ஜெட் வெற்றிகரமாக நீக்கப்பட்டது',
    'confirm-delete-budget': 'இந்த பட்ஜெட்டை நீக்க விரும்புகிறீர்களா?',
    'remaining': 'மீதமுள்ள',
    'over-budget': 'பட்ஜெட்டை மீறியது',
    'on-track': 'பாதையில்',
    'budget-progress': 'பட்ஜெட் முன்னேற்றம்',
    'spent': 'செலவு',
    'available': 'கிடைக்கும்',
    'budget-overview': 'பட்ஜெட் கண்ணோட்டம்',
    'monitor-spending': 'உங்கள் செலவினங்களை கண்காணித்து பாதையில் இருங்கள்',
    'total-budget': 'மொத்த பட்ஜெட்',
    'total-spent': 'மொத்த செலவு',
    'add-new-budget': 'புதிய பட்ஜெட் சேர்க்கவும்',
    'budget-name-placeholder': 'எ.கா., கடை',
    'active-budget': 'செயலில் உள்ள பட்ஜெட்',
      'update-budget': 'பட்ஜெட்டை புதுப்பிக்கவும்',
      'create-budget': 'பட்ஜெட்டை உருவாக்கவும்',
      'no-budgets-yet': 'இன்னும் பட்ஜெட் இல்லை',
    'create-first-budget': 'உங்கள் செலவினங்களை கண்காணிக்கத் தொடங்க உங்கள் முதல் பட்ஜெட்டை உருவாக்கவும்',
    'create-first-budget-button': 'உங்கள் முதல் பட்ஜெட்டை உருவாக்கவும்',
    
    // Goals
    'add-goal': 'இலக்கு சேர்க்கவும்',
    'edit-goal': 'இலக்கை திருத்தவும்',
    'goal-name': 'இலக்கு பெயர்',
    'target-amount': 'இலக்கு தொகை',
    'current-amount': 'தற்போதைய தொகை',
    'target-date': 'இலக்கு தேதி',
    'status': 'நிலை',
    'completed': 'முடிந்தது',
    'paused': 'இடைநிறுத்தப்பட்டது',
    'cancelled': 'ரத்து செய்யப்பட்டது',
    'progress': 'முன்னேற்றம்',
    'goal-created': 'இலக்கு வெற்றிகரமாக உருவாக்கப்பட்டது',
    'goal-updated': 'இலக்கு வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    'goal-deleted': 'இலக்கு வெற்றிகரமாக நீக்கப்பட்டது',
    'confirm-delete-goal': 'இந்த இலக்கை நீக்க விரும்புகிறீர்களா?',
    'days-remaining': 'மீதமுள்ள நாட்கள்',
    'goal-description': 'இலக்கு விளக்கம்',
    'goal-progress': 'இலக்கு முன்னேற்றம்',
    'target': 'இலக்கு',
    'achieved': 'அடையப்பட்டது',
    'financial-goals': 'நிதி இலக்குகள்',
    'track-progress': 'நிதி மைல்கற்களுக்கு உங்கள் முன்னேற்றத்தை கண்காணியுங்கள்',
    'add-new-goal': 'புதிய இலக்கு சேர்க்கவும்',
    'goal-name-placeholder': 'எ.கா., அவசர நிதி',
    'describe-goal': 'உங்கள் இலக்கை விவரிக்கவும்...',
    'update-goal': 'இலக்கை புதுப்பிக்கவும்',
    'create-goal': 'இலக்கை உருவாக்கவும்',
    'no-goals-yet': 'இன்னும் இலக்குகள் இல்லை',
    'create-first-goal': 'தொடங்க உங்கள் முதல் நிதி இலக்கை உருவாக்கவும்',
    'create-first-goal-button': 'உங்கள் முதல் இலக்கை உருவாக்கவும்',
    
    // AI Advisor
    'ask-ai': 'ஏஐ-க்கு கேளுங்கள்',
    'ai-thinking': 'ஏஐ சிந்திக்கிறது...',
    'ai-response': 'ஏஐ பதில்',
    'ask-question': 'உங்கள் நிதியைப் பற்றி கேள்வி கேளுங்கள்...',
    'clear-conversation': 'உரையாடலை அழிக்கவும்',
    'recent-queries': 'சமீபத்திய கேள்விகள்',
    'ai-categories': 'ஏஐ வகைகள்',
    'budgeting-tip': 'பட்ஜெட் உதவி',
    'savings-advice': 'சேமிப்பு ஆலோசனை',
    'investment-tip': 'முதலீட்டு உதவி',
    'financial-insight': 'நிதி நுண்ணறிவு',
    'get-advice': 'ஆலோசனை பெறுங்கள்',
    'ai-financial-advisor': 'ஏஐ நிதி ஆலோசகர்',
    'ai-advisor-description': 'ஏஐ இயக்கப்படும் தனிப்பட்ட நிதி ஆலோசனையைப் பெறவும். பட்ஜெட், முதலீடு, சேமிப்பு அல்லது எந்த நிதி தலைப்பு பற்றியும் கேள்விகள் கேளுங்கள்.',
    'ask-financial-question': 'உங்கள் நிதி கேள்வியைக் கேளுங்கள்',
    'ai-question-placeholder': 'எ.கா., நான் எப்படி அதிக பணம் சேமிக்க முடியும்? நான் பங்குகளில் முதலீடு செய்ய வேண்டுமா? அவசர நிதியில் எவ்வளவு இருக்க வேண்டும்?',
    'quick-questions': 'விரைவு கேள்விகள்',
    'quick-question-1': 'நான் எப்படி அதிக பணம் சேமிக்க முடியும்?',
    'quick-question-2': 'நான் பங்குகளில் அல்லது மியூச்சுவல் ஃபண்டுகளில் முதலீடு செய்ய வேண்டுமா?',
    'quick-question-3': 'அவசர நிதியில் எவ்வளவு இருக்க வேண்டும்?',
    'quick-question-4': '50/30/20 விதி என்ன?',
    'quick-question-5': 'நான் எப்படி பட்ஜெட் உருவாக்குவது?',
    'quick-question-6': 'நான் எப்போது முதலீடு தொடங்க வேண்டும்?',
    'ai-advice': 'ஏஐ ஆலோசனை',
    'recent-conversations': 'சமீபத்திய உரையாடல்கள்',
    'previous-ai-interactions': 'உங்கள் முந்தைய ஏஐ உரையாடல்கள்',
    'no-conversations-yet': 'இன்னும் உரையாடல்கள் இல்லை',
    'start-asking-question': 'மேலே ஒரு நிதி கேள்வியைக் கேட்பதன் மூலம் தொடங்கவும்',
    'failed-load-ai-history': 'ஏஐ வரலாற்றை ஏற்ற முடியவில்லை',
    'failed-get-ai-advice': 'ஏஐ ஆலோசனையைப் பெற முடியவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    
    // Settings
    'profile': 'சுயவிவரம்',
    'notifications': 'அறிவிப்புகள்',
    'security': 'பாதுகாப்பு',
    'name': 'பெயர்',
    'email': 'மின்னஞ்சல்',
    'phone': 'தொலைபேசி',
    'avatar': 'அவதாரம்',
    'update-profile': 'சுயவிவரத்தை புதுப்பிக்கவும்',
    'email-notifications': 'மின்னஞ்சல் அறிவிப்புகள்',
    'push-notifications': 'புஷ் அறிவிப்புகள்',
    'sms-notifications': 'SMS அறிவிப்புகள்',
    'weekly-report': 'வாராந்திர அறிக்கை',
    'budget-alerts': 'பட்ஜெட் எச்சரிக்கைகள்',
    'goal-reminders': 'இலக்கு நினைவூட்டல்கள்',
    'theme': 'தீம்',
    'light': 'வெளிச்சம்',
    'dark': 'இருட்டு',
    'auto': 'தானியங்கி',
    'date-format': 'தேதி வடிவம்',
    'two-factor-auth': 'இரண்டு-காரணி அங்கீகாரம்',
    'change-password': 'கடவுச்சொல்லை மாற்றவும்',
    'last-login': 'கடைசி உள்நுழைவு',
    'profile-updated': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
    'settings-saved': 'அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டன',
    'account-security': 'கணக்கு பாதுகாப்பு',
    'password-changed': 'கடவுச்சொல் மாற்றப்பட்டது',
    'manage-account-settings': 'உங்கள் கணக்கு அமைப்புகள் மற்றும் விருப்பங்களை நிர்வகிக்கவும்',
    'profile-information': 'சுயவிவர தகவல்',
    'change-avatar': 'அவதாரத்தை மாற்றவும்',
    'full-name': 'முழு பெயர்',
    'notification-preferences': 'அறிவிப்பு விருப்பங்கள்',
    'receive-updates-email': 'மின்னஞ்சல் மூலம் புதுப்பிப்புகளைப் பெறவும்',
    'get-notified-device': 'உங்கள் சாதனத்தில் அறிவிப்பு பெறவும்',
    'receive-text-messages': 'உரை செய்திகளைப் பெறவும்',
    'get-weekly-summaries': 'வாராந்திர நிதி சுருக்கங்களைப் பெறவும்',
    'notify-budget-limits': 'பட்ஜெட் வரம்புகளை அடையும்போது அறிவிக்கவும்',
      'remind-financial-goals': 'நிதி இலக்குகளைப் பற்றி நினைவூட்டவும்',
      'app-preferences': 'பயன்பாட்டு விருப்பங்கள்',
      'security-privacy': 'பாதுகாப்பு மற்றும் தனியுரிமை',
    'update-password-secure': 'உங்கள் கணக்கை பாதுகாப்பாக வைத்திருக்க உங்கள் கடவுச்சொல்லை புதுப்பிக்கவும்',
    'add-extra-security': 'உங்கள் கணக்கில் கூடுதல் பாதுகாப்பு அடுக்கைச் சேர்க்கவும்',
    'enable-2fa': '2FA இயக்கவும்',
    'data-export': 'தரவு ஏற்றுமதி',
    'download-financial-data': 'உங்கள் நிதி தரவின் நகலைப் பதிவிறக்கவும்',
    'export-data': 'தரவை ஏற்றுமதி செய்யவும்',
    'save-changes': 'மாற்றங்களை சேமிக்கவும்',
    'auto-saved': 'தானாக சேமிக்கப்பட்டது',
    
    // Password Change
    'current-password': 'தற்போதைய கடவுச்சொல்',
    'new-password': 'புதிய கடவுச்சொல்',
    'confirm-password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'password-mismatch': 'கடவுச்சொற்கள் பொருந்தவில்லை',
    'password-changed-success': 'கடவுச்சொல் வெற்றிகரமாக மாற்றப்பட்டது',
    'password-min-length': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகளாக இருக்க வேண்டும்',
    
    // Sign In
    'sign-in': 'உள்நுழையவும்',
    'sign-up': 'பதிவு செய்யவும்',
    'email-address': 'மின்னஞ்சல் முகவரி',
    'password': 'கடவுச்சொல்',
    'forgot-password': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    'login-success': 'உள்நுழைவு வெற்றிகரமானது',
    'login-error': 'உள்நுழைவு தோல்வி',
    'invalid-credentials': 'தவறான அங்கீகாரங்கள்',
    'enter-email': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    'enter-password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'remember-me': 'என்னை நினைவில் வைத்துக்கொள்ளுங்கள்',
    'dont-have-account': 'கணக்கு இல்லையா?',
    'already-have-account': 'ஏற்கனவே கணக்கு உள்ளதா?'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<string>(() => {
    // Get language from localStorage or default to English
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (language: string) => {
    setCurrentLanguage(language);
    localStorage.setItem('language', language);
  };

  const t = (key: string): string => {
    const langTranslations = translations[currentLanguage] || translations.en;
    return langTranslations[key] || translations.en[key] || key;
  };

  const value: LanguageContextType = {
    currentLanguage,
    setLanguage,
    t,
    languages
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
